# Generated by Django 5.1.2 on 2024-10-23 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='distance',
            field=models.FloatField(),
        ),
    ]
