# Generated by Django 5.1.2 on 2024-10-23 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0002_alter_route_distance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='route',
            name='start_time',
        ),
    ]
