# Generated by Django 5.1.2 on 2024-10-23 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0003_remove_route_end_time_remove_route_start_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='vehicles',
        ),
    ]
