# Generated by Django 5.1.2 on 2024-10-23 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0004_remove_route_vehicles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='route_name',
        ),
    ]
