# Generated by Django 5.1.2 on 2024-11-18 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0005_remove_route_route_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='average_speed',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='route',
            name='total_revenue',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='route',
            name='total_trips',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
