# Generated by Django 5.1.2 on 2024-11-18 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='average_trip_time',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='total_earnings',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='driver',
            name='total_trips',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
