# Generated by Django 5.1.2 on 2024-10-22 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='category',
            field=models.CharField(choices=[('taxi', 'Taxi'), ('cab', 'Cab'), ('bus', 'Bus'), ('coaster', 'Coaster (Minibus)'), ('coach', 'Coach'), ('bike', 'Bike'), ('van', 'Van')], default=('taxi', 'Taxi'), max_length=50),
        ),
    ]
