# Generated by Django 5.1.2 on 2024-11-18 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0003_vehicle_route'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='total_distance',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='total_trips',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
